# Generated by Django 2.0 on 2018-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0002_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='createTime',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='info',
            new_name='function_info',
        ),
        migrations.AddField(
            model_name='action',
            name='request_info',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
