# Generated by Django 2.0 on 2018-05-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0005_quickloginrecord_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickloginrecord',
            name='verification_code',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
