# Generated by Django 2.0 on 2018-05-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0006_auto_20180517_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickloginrecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
