# Generated by Django 2.0 on 2018-06-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0007_quickloginrecord_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restemplate',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
