# Generated by Django 2.0 on 2018-06-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0008_restemplate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='responseTemplates',
        ),
        migrations.AddField(
            model_name='restemplate',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dal.Project'),
        ),
    ]
