# Generated by Django 2.0 on 2018-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0011_auto_20180615_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='responseJson',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
