# Generated by Django 2.0 on 2018-06-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0012_api_responsejson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='resTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dal.ResTemplate'),
        ),
    ]
