# Generated by Django 2.0 on 2018-06-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0015_auto_20180615_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='responseJson',
        ),
    ]
